import { MenuItem } from "./menu-types.js";


export const combosMenu: MenuItem[] = [
  {
    id: 401,
    name: "Chicken Combo",
    description: "Chicken Breast 2-Skewer Bowl + Side Fries (200g) + 500ml drink",
    price: 23.99,
    image: "/assets/chicken-combo.jpeg",
    category: "Combos",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: [],
  },
  {
    id: 402,
    name: "Premium Combo",
    description: "Lamb / Goat / Salmon 2-Skewer Bowl + Side Fries (200g) + 500ml drink",
    price: 26.99,
    image: "/assets/premium-combo.jpeg",
    category: "Combos",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: [],
  },
  {
    id: 404,
    name: "Kids Combo",
    description: "Kids Bowl (Chicken or Paneer Tikka)+10 Oz Drink (Any Flavor/ Shake/ Blend /Og)",
    price: 9.99,
    image: "/assets/kids-combo.jpeg",
    category: "Combos",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: [],
    sidePairings: [],
  },
  {
    id: 405,
    name: "Veg Combo",
    description: "Paneer or Soya 2-Skewer Bowl + Fries (200g) + 500ml drink",
    price: 19.49,
    image: "/assets/Veg-Combo.jpeg",
    category: "Combos",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: ["milk", "soy"],
    dietary: ["vegetarian", "vegan"],
    sidePairings: []
  }
];
