import { MenuItem } from "./menu-types.js";


export const kidsMenu: MenuItem[] = [
  {
    id: 401,
    name: "Kids Drink (10 Oz)",
    description: "Real-Fruit Shake. Real Fruit Blend / Fresh Orange Juice.",
    price: 3.49,
    image: "/assets/kids-drink.jpeg",
    category: "Kids Menu",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: [],
    sidePairings: [],
  },
  {
    id: 402,
    name: "Kids Bowl Paneer",
    description: "80G Paneer Cubes (Tikka)+ Base+1 Sauce",
    price: 5.99,
    image: "/assets/kids-bowl-paneer.jpeg",
    category: "Kids Menu",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: [],
    sidePairings: [],
  },
  {
    id: 403,
    name: "Kids Bowl Chicken",
    description: "80G Chicken Breast Cubes(Tikka)+1 Base +1 Sauce",
    price: 6.99,
    image: "/assets/kids-bowl-chicken.jpeg",
    category: "Kids Menu",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: [],
    sidePairings: [],
  },
  {
    id: 404,
    name: "Kids Combo",
    description: "Kids Bowl (Chicken or Paneer Tikka)+10 Oz Drink (Any Flavor/ Shake/ Blend /Og)",
    price: 9.99,
    image: "/assets/kids-combo.jpeg",
    category: "Kids Menu",
    heatLevel: 0,
    isPopular: false,
    saucePairings: [],
    customizations: [],
    allergens: [],
    dietary: [],
    sidePairings: [],
  },
];
