import { MenuItem } from "./menu-types.js";


export const proteinCubeSkewerPlatters: MenuItem[] = [
  {
    id: 1,
    name: "Chicken Breast Cubes",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad. 1-Skewer 11.99 / 2-Skewers 15.99 / 3 Skewers 17.99",
    image: "/assets/chicken.jpeg",
    category: "Protein Cube Skewer Platter",
    heatLevel: 2,
    isPopular: true,
    addOns: ["Extra Chicken Skewer 4.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 11.99,
  },
  {
    id: 2,
    name: "Lamb Cubes",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad. 1-Skewer 13.99 / 2-Skewers 17.99 / 3 Skewers 25.99",
    image: "/assets/lamb.jpeg",
    category: "Protein Cube Skewer Platter",
    heatLevel: 3,
    isPopular: true,
    addOns: ["Extra Lamb Skewer 5.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 13.99,
  },
  {
    id: 3,
    name: "Goat Cubes",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad. 1-Skewer 13.99 / 2-Skewers 17.99 / 3 Skewers 23.99",
    image: "/assets/goat-cubes.jpeg",
    category: "Protein Cube Skewer Platter",
    heatLevel: 3,
    isPopular: true,
    addOns: ["Extra Goat Skewer 5.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 13.99,
  },
  {
    id: 4,
    name: "Paneer Cubes",
    description: "Indian Cheese Cubes. Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad. 1-Skewer 9.99 / 2-Skewers 13.99 / 3 Skewers 17.99",
    image: "/assets/paneer.jpeg",
    category: "Protein Cube Skewer Platter",
    heatLevel: 1,
    isPopular: false,
    addOns: ["Extra Paneer Skewer 3.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 9.99,
  },
  {
    id: 5,
    name: "Soya Cubes",
    description: "Plant-Based Cubes. Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad. 1-Skewer 9.99 / 2-Skewers 13.99 / 3 Skewers 17.99",
    image: "/assets/soya-chaap.jpeg",
    category: "Protein Cube Skewer Platter",
    heatLevel: 2,
    isPopular: false,
    addOns: ["Extra Soya Skewer 3.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["soy"],
    dietary: ["vegan", "gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 9.99,
  },
];
