import { MenuItem } from "./menu-types.js";

export const shakesAndJuices: Record<string, MenuItem[]> = {
  "REAL FRUIT SHAKES & FRUIT BLENDS": [
    // Signature Shakes
    {
      id: 201,
      name: "Mango Shake",
      description: "Real mango + milk + cream. 1 real fruit free: Pineapple or Coconut.",
      price: 6.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
      isPopular: true,
    },
    {
      id: 202,
      name: "Strawberry Shake",
      description: "Real strawberry + milk + cream. 1 real fruit free: Banana or Mango.",
      price: 6.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 203,
      name: "Coconut Shake",
      description: "Real coconut + pineapple + milk. 1 real fruit free: Mango or Pineapple.",
      price: 6.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 204,
      name: "All Berry Shake",
      description: "4 real berries + milk + cream. 1 real fruit free: Banana or Peach.",
      price: 7.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 205,
      name: "Almond Date Shake",
      description: "Dates + almonds + honey + milk. 1 real fruit free: Banana.",
      price: 6.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk", "tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    // Popular Fruit Blends
    {
      id: 206,
      name: "Blue Lagoon",
      description: "Pineapple + Mango + Banana + Blue Spirulina (Water Base)",
      price: 8.48,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
      isPopular: true,
    },
    {
      id: 207,
      name: "Tropical Blend",
      description: "Mango + Pineapple + Coconut (Water Base)",
      price: 7.49,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 208,
      name: "Berry Burst Blend",
      description: "Strawberry + Blueberry + Raspberry (Water Base)",
      price: 7.49,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 209,
      name: "Sunrise Blend",
      description: "Mango + Peach + Pineapple (Water Base)",
      price: 7.49,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 210,
      name: "Watermelon Cooler",
      description: "Watermelon + Mint + Lime juice (Water Base)",
      price: 7.49,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 211,
      name: "Green Blend",
      description: "Spinach + Mango + Pineapple + Banana (Water Base)",
      price: 7.49,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    // Build Your Own (as a single menu item for UI, fruits as reference below)
    {
      id: 220,
      name: "Build Your Own Shake or Blend",
      description: "Pick up to 3 fruits. Shake (Milk+Cream) $6.99 | Fruit Blend (No Dairy, Water Base) $7.49",
      price: 6.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Build Your Own",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
      isNew: true,
    },
    // Indulgent Flavors (Shake base only)
    {
      id: 230,
      name: "Chocolate (Indulgent Flavor)",
      description: "Shake base only. Contains SOY. Goes with Banana, PB, Cherry, Hazelnut, Espresso.",
      price: 0.0,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Indulgent Flavors",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["soy"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 231,
      name: "Biscoff (Indulgent Flavor)",
      description: "Shake base only. Contains WHEAT (gluten). Goes with Banana, Chocolate.",
      price: 0.0,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Indulgent Flavors",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["gluten"],
      dietary: ["vegetarian"],
    },
    {
      id: 232,
      name: "Hazelnut (Indulgent Flavor)",
      description: "Shake base only. Contains TREE-NUTS. Goes with Banana, Chocolate.",
      price: 0.0,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Indulgent Flavors",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    // Add-ons
    {
      id: 240,
      name: "Protein Add-on",
      description: "Protein 25g +$1.99",
      price: 1.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 241,
      name: "Collagen Add-on",
      description: "Collagen 10g +$1.99",
      price: 1.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["gluten-free"],
    },
    {
      id: 242,
      name: "Chia/Flax Add-on",
      description: "Chia/Flax 10g +$0.79",
      price: 0.79,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "gluten-free"],
    },
    {
      id: 243,
      name: "Nut Top Add-on",
      description: "Nut Top +$0.69",
      price: 0.69,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 244,
      name: "Oat Milk Add-on",
      description: "Oat Milk +$0.79",
      price: 0.79,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["gluten"],
      dietary: ["vegan"],
    },
    {
      id: 245,
      name: "Almond Milk Add-on",
      description: "Almond Milk +$0.69",
      price: 0.69,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["tree-nuts"],
      dietary: ["vegan", "gluten-free"],
    },
    {
      id: 246,
      name: "Yogurt Add-on",
      description: "Yogurt +$0.79",
      price: 0.79,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 247,
      name: "Blue Spirulina Add-on",
      description: "Blue Spirulina +$0.99",
      price: 0.99,
      image: "",
      category: "Shakes & Juices",
      subCategory: "Add-ons",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "gluten-free"],
    },
  ],
};