// src/lib/shakes-juices-data.ts
import { MenuItem } from "./menu-types.js";

// All image fields below use string paths to public/assets/shakes/ and public/assets/blends/


export const shakesAndJuices: Record<string, MenuItem[]> = {
  "Shakes": [
    {
      id: 202,
      name: "Strawberry Shake",
      description: "Real Strawberry + Milk + Cream",
      pricestandard: 7.99,
      image: "/assets/shakes/Strawberry-Shake.jpeg",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk", "tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 201,
      name: "Golden Mango",
      description: "Real Alphonso Mango + Milk + Cream",
      priceStandard: 7.99,
      image: "/assets/shakes/Mango-Shake.jpeg",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: ["milk", "tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    // Duplicate All Berry Shake removed
    {
      id: 204,
      name: "All Berry Shake",
      description: "Strawberry + Blueberry + Raspberry + Blackberry",
      pricestandard: 7.99,
      pricecombo: 8.99,
      image: "/assets/shakes/All-Berry-Shake.jpeg",
      category: "Shakes & Juices",
      subCategory: "Signature Shakes",
      heatLevel: 0,
      saucePairings: [],
      allergens: ["milk", "tree-nuts"],
      dietary: ["vegetarian", "gluten-free"],
    },
    {
      id: 303,
      name: "Berry Burst",
      description: "Strawberry + Blueberry + Raspberry",
      pricestandard: 7.99,
      pricecombo: 8.99,
      image: "/assets/blends/Berry-Burst-Blend.jpeg",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 304,
      name: "Sunrise Breeze",
      description: "Mango + peach + pineapple",
      pricestandard: 7.99,
      pricecombo: 8.99,
      image: "/assets/blends/Sunrise-Blend.jpeg",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
    {
      id: 305,
      name: "Watermelon Cooler",
      description: "Watermelon + mint + lime · seasonal",
      pricestandard: 7.99,
      pricecombo: 8.99,
      image: "/assets/blends/Watermelon-Cooler.jpeg",
      category: "Shakes & Juices",
      subCategory: "Popular Fruit Blends",
      heatLevel: 0,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "dairy-free", "gluten-free", "nut-free"],
    },
  ],
};