import { MenuItem } from "./menu-types.js";


export const sidesItems: Record<string, MenuItem[]> = {
  Salads: [
    {
      id: 301,
      name: "Cucumber Tomato",
      description: "Fresh Cucumber, Ripe Tomato, Lime, Olive Oil\n70G per Scoop Price: 5.99",
      image: "/assets/cucumber-tomato.jpeg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 0,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
    },
    {
      id: 303,
      name: "Pickled Onion",
      description: "Quick-Pickled Red Onion, Mustard Seed\n70G per Scoop Price: 5.99",
      image: "/assets/pickled-onion.jpeg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 0,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
    },
    {
      id: 304,
      name: "Sweet Corn & Pepper",
      description: "Sweet Corn, Bell Pepper, Tamarind-Hint\n70G per Scoop Price: 5.99",
      image: "/assets/sweet-corn.jpeg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 0,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      isPopular: true,
    },
    {
      id: 306,
      name: "Lazzat Bean Salad",
      description: "Kidney Bean, Raisin, Mild Spice\n70G per Scoop Price: 5.99",
      image: "/assets/lazzat-bean-salad.jpeg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 0,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      isPopular: true,
    },
    {
      id: 307,
      name: "Spiced ChickPea",
      description: "Chickpea, Lemon, Mild Spice\nHoney Based Dressing\n70G per Scoop Price: 5.99",
      image: "/assets/spiced-chickpea.jpeg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 2,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
    },
    {
      id: 308,
      name: "Roasted Sweet Potato",
      description: "Roasted Cubed Sweet Potato, Herbs\n70G per Scoop Price:5.99",
      image: "/assets/roasted-potato.jpg",
      category: "Salads",
      subCategory: "Salads",
      heatLevel: 0,
      price: 5.99,
      saucePairings: [],
      customizations: [],
      allergens: [],
      dietary: ["vegan", "vegetarian", "gluten-free"],
    },
  ],
};